export const CV_FOLDER_APPLICATIONS = 'CV_FOLDER_APPLICATIONS';
export const JOB_POST_APPLICATIONS = 'JOB_POST_APPLICATIONS';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const APPLICATION_DIALOG = 'APPLICATION_DIALOG';