export const LAST_FIVE_JOB_POSTS = 'LAST_FIVE_JOB_POSTS';
export const WAITING_JOB_POSTS = 'WAITING_JOB_POSTS';
export const LIVE_JOB_POSTS = 'LIVE_JOB_POSTS';
export const EXPIRED_JOB_POSTS = 'EXPIRED_JOB_POSTS';
export const PUBLIC_JOB_POSTS = 'PUBLIC_JOB_POSTS';
export const JOB_BOARD_JOB_EMAIL_TEMPLATE = 'JOB_BOARD_JOB_EMAIL_TEMPLATE';
export const EMAIL_TEMPLATE_MODAL = 'EMAIL_TEMPLATE_MODAL';
